version: "3.5"

services: 
  front-control361:
   container_name: front-control361
   build: 
    context: .
    dockerfile: Dockerfile.dev
   restart: always
   ports:
    - 3000:3000
   volumes:
    - .:/app/front-control361
    - /app/front-control361/node_modules
    - /app/front-control361/.next
 
